services:
  db:
    image: acedroidx/destinychildserver-db:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  server:
    image: acedroidx/destinychildserver-server:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 123456
      season_raid: 12 #/**raid赛季id 0-56*/
      season_world: 14 #世界boss1到38
      season_level_max: 1 #1获得物品角色自动满级 其他值不满级.
    depends_on:
      - db